
backend:
  name: github
  repo: youkyll/youkyll-blog
  branch: master

media_folder: static/img
public_folder: /img

publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}---{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

media_library:
  name: cloudinary
  config:
    cloud_name: davkbtsa4
    api_key: 153758269172829
